apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tzg4ajkvl-nodejs 
  janus-idp.io/tekton: tzg4ajkvl-nodejs
  backstage.io/kubernetes-id: tzg4ajkvl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tzg4ajkvl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  