apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tzg4ajkvl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tzg4ajkvl-nodejs 
  name: tzg4ajkvl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tzg4ajkvl-nodejs 
